---

- name: Add repository
  yum_repository:
    name: nginx
    description: Nginx Repo
    baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/

- name: Install pkg
  yum: name=nginx state=latest disable_gpg_check=yes

- name: Config defalt.conf
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
